/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PanelistIndexRouteImport } from './routes/panelist/index'
import { Route as FacultyIndexRouteImport } from './routes/faculty/index'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as PanelistReviewsRouteImport } from './routes/panelist/reviews'
import { Route as PanelistDecisionsRouteImport } from './routes/panelist/decisions'
import { Route as FacultyDocumentsRouteImport } from './routes/faculty/documents'
import { Route as FacultyApplicationsRouteImport } from './routes/faculty/applications'
import { Route as publicSignupRouteImport } from './routes/(public)/signup'
import { Route as publicSignInRouteImport } from './routes/(public)/sign-in'
import { Route as publicHomeRouteImport } from './routes/(public)/home'
import { Route as publicAboutRouteImport } from './routes/(public)/about'

const PanelistIndexRoute = PanelistIndexRouteImport.update({
  id: '/panelist/',
  path: '/panelist/',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyIndexRoute = FacultyIndexRouteImport.update({
  id: '/faculty/',
  path: '/faculty/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelistReviewsRoute = PanelistReviewsRouteImport.update({
  id: '/panelist/reviews',
  path: '/panelist/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelistDecisionsRoute = PanelistDecisionsRouteImport.update({
  id: '/panelist/decisions',
  path: '/panelist/decisions',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyDocumentsRoute = FacultyDocumentsRouteImport.update({
  id: '/faculty/documents',
  path: '/faculty/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyApplicationsRoute = FacultyApplicationsRouteImport.update({
  id: '/faculty/applications',
  path: '/faculty/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const publicSignupRoute = publicSignupRouteImport.update({
  id: '/(public)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const publicSignInRoute = publicSignInRouteImport.update({
  id: '/(public)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const publicHomeRoute = publicHomeRouteImport.update({
  id: '/(public)/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const publicAboutRoute = publicAboutRouteImport.update({
  id: '/(public)/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/about': typeof publicAboutRoute
  '/home': typeof publicHomeRoute
  '/sign-in': typeof publicSignInRoute
  '/signup': typeof publicSignupRoute
  '/faculty/applications': typeof FacultyApplicationsRoute
  '/faculty/documents': typeof FacultyDocumentsRoute
  '/panelist/decisions': typeof PanelistDecisionsRoute
  '/panelist/reviews': typeof PanelistReviewsRoute
  '/': typeof publicIndexRoute
  '/faculty/': typeof FacultyIndexRoute
  '/panelist/': typeof PanelistIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof publicAboutRoute
  '/home': typeof publicHomeRoute
  '/sign-in': typeof publicSignInRoute
  '/signup': typeof publicSignupRoute
  '/faculty/applications': typeof FacultyApplicationsRoute
  '/faculty/documents': typeof FacultyDocumentsRoute
  '/panelist/decisions': typeof PanelistDecisionsRoute
  '/panelist/reviews': typeof PanelistReviewsRoute
  '/': typeof publicIndexRoute
  '/faculty': typeof FacultyIndexRoute
  '/panelist': typeof PanelistIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(public)/about': typeof publicAboutRoute
  '/(public)/home': typeof publicHomeRoute
  '/(public)/sign-in': typeof publicSignInRoute
  '/(public)/signup': typeof publicSignupRoute
  '/faculty/applications': typeof FacultyApplicationsRoute
  '/faculty/documents': typeof FacultyDocumentsRoute
  '/panelist/decisions': typeof PanelistDecisionsRoute
  '/panelist/reviews': typeof PanelistReviewsRoute
  '/(public)/': typeof publicIndexRoute
  '/faculty/': typeof FacultyIndexRoute
  '/panelist/': typeof PanelistIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/about'
    | '/home'
    | '/sign-in'
    | '/signup'
    | '/faculty/applications'
    | '/faculty/documents'
    | '/panelist/decisions'
    | '/panelist/reviews'
    | '/'
    | '/faculty/'
    | '/panelist/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/home'
    | '/sign-in'
    | '/signup'
    | '/faculty/applications'
    | '/faculty/documents'
    | '/panelist/decisions'
    | '/panelist/reviews'
    | '/'
    | '/faculty'
    | '/panelist'
  id:
    | '__root__'
    | '/(public)/about'
    | '/(public)/home'
    | '/(public)/sign-in'
    | '/(public)/signup'
    | '/faculty/applications'
    | '/faculty/documents'
    | '/panelist/decisions'
    | '/panelist/reviews'
    | '/(public)/'
    | '/faculty/'
    | '/panelist/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  publicAboutRoute: typeof publicAboutRoute
  publicHomeRoute: typeof publicHomeRoute
  publicSignInRoute: typeof publicSignInRoute
  publicSignupRoute: typeof publicSignupRoute
  FacultyApplicationsRoute: typeof FacultyApplicationsRoute
  FacultyDocumentsRoute: typeof FacultyDocumentsRoute
  PanelistDecisionsRoute: typeof PanelistDecisionsRoute
  PanelistReviewsRoute: typeof PanelistReviewsRoute
  publicIndexRoute: typeof publicIndexRoute
  FacultyIndexRoute: typeof FacultyIndexRoute
  PanelistIndexRoute: typeof PanelistIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/panelist/': {
      id: '/panelist/'
      path: '/panelist'
      fullPath: '/panelist/'
      preLoaderRoute: typeof PanelistIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/': {
      id: '/faculty/'
      path: '/faculty'
      fullPath: '/faculty/'
      preLoaderRoute: typeof FacultyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panelist/reviews': {
      id: '/panelist/reviews'
      path: '/panelist/reviews'
      fullPath: '/panelist/reviews'
      preLoaderRoute: typeof PanelistReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panelist/decisions': {
      id: '/panelist/decisions'
      path: '/panelist/decisions'
      fullPath: '/panelist/decisions'
      preLoaderRoute: typeof PanelistDecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/documents': {
      id: '/faculty/documents'
      path: '/faculty/documents'
      fullPath: '/faculty/documents'
      preLoaderRoute: typeof FacultyDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/applications': {
      id: '/faculty/applications'
      path: '/faculty/applications'
      fullPath: '/faculty/applications'
      preLoaderRoute: typeof FacultyApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/signup': {
      id: '/(public)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof publicSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/sign-in': {
      id: '/(public)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof publicSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/home': {
      id: '/(public)/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof publicHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/about': {
      id: '/(public)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof publicAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  publicAboutRoute: publicAboutRoute,
  publicHomeRoute: publicHomeRoute,
  publicSignInRoute: publicSignInRoute,
  publicSignupRoute: publicSignupRoute,
  FacultyApplicationsRoute: FacultyApplicationsRoute,
  FacultyDocumentsRoute: FacultyDocumentsRoute,
  PanelistDecisionsRoute: PanelistDecisionsRoute,
  PanelistReviewsRoute: PanelistReviewsRoute,
  publicIndexRoute: publicIndexRoute,
  FacultyIndexRoute: FacultyIndexRoute,
  PanelistIndexRoute: PanelistIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
