/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PanelistIndexRouteImport } from './routes/panelist/index'
import { Route as FacultyIndexRouteImport } from './routes/faculty/index'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as PanelistReviewsRouteImport } from './routes/panelist/reviews'
import { Route as PanelistDecisionsRouteImport } from './routes/panelist/decisions'
import { Route as PanelistChatRouteImport } from './routes/panelist/chat'
import { Route as FacultyDocumentsRouteImport } from './routes/faculty/documents'
import { Route as FacultyChatRouteImport } from './routes/faculty/chat'
import { Route as FacultyApplicationsRouteImport } from './routes/faculty/applications'
import { Route as publicSignupRouteImport } from './routes/(public)/signup'
import { Route as publicSignInRouteImport } from './routes/(public)/sign-in'
import { Route as publicResetSuccessRouteImport } from './routes/(public)/reset-success'
import { Route as publicResetPasswordRouteImport } from './routes/(public)/reset-password'
import { Route as publicHomeRouteImport } from './routes/(public)/home'
import { Route as publicForgotPasswordRouteImport } from './routes/(public)/forgot-password'
import { Route as ApiV1HealthRouteImport } from './routes/api/v1/health'
import { Route as ApiV1AuthSignUpRouteImport } from './routes/api/v1/auth/sign-up'
import { Route as ApiV1AuthSignOutRouteImport } from './routes/api/v1/auth/sign-out'
import { Route as ApiV1AuthSignInRouteImport } from './routes/api/v1/auth/sign-in'
import { Route as ApiV1AuthResetPasswordRouteImport } from './routes/api/v1/auth/reset-password'
import { Route as ApiV1AuthMeRouteImport } from './routes/api/v1/auth/me'
import { Route as ApiV1AuthForgotPasswordRouteImport } from './routes/api/v1/auth/forgot-password'
import { Route as ApiV1AuthEmailStatusRouteImport } from './routes/api/v1/auth/email-status'
import { Route as ApiV1AppwriteTablesRouteImport } from './routes/api/v1/appwrite/tables'
import { Route as ApiV1AppwriteHealthRouteImport } from './routes/api/v1/appwrite/health'

const PanelistIndexRoute = PanelistIndexRouteImport.update({
  id: '/panelist/',
  path: '/panelist/',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyIndexRoute = FacultyIndexRouteImport.update({
  id: '/faculty/',
  path: '/faculty/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelistReviewsRoute = PanelistReviewsRouteImport.update({
  id: '/panelist/reviews',
  path: '/panelist/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelistDecisionsRoute = PanelistDecisionsRouteImport.update({
  id: '/panelist/decisions',
  path: '/panelist/decisions',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelistChatRoute = PanelistChatRouteImport.update({
  id: '/panelist/chat',
  path: '/panelist/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyDocumentsRoute = FacultyDocumentsRouteImport.update({
  id: '/faculty/documents',
  path: '/faculty/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyChatRoute = FacultyChatRouteImport.update({
  id: '/faculty/chat',
  path: '/faculty/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyApplicationsRoute = FacultyApplicationsRouteImport.update({
  id: '/faculty/applications',
  path: '/faculty/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const publicSignupRoute = publicSignupRouteImport.update({
  id: '/(public)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const publicSignInRoute = publicSignInRouteImport.update({
  id: '/(public)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const publicResetSuccessRoute = publicResetSuccessRouteImport.update({
  id: '/(public)/reset-success',
  path: '/reset-success',
  getParentRoute: () => rootRouteImport,
} as any)
const publicResetPasswordRoute = publicResetPasswordRouteImport.update({
  id: '/(public)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const publicHomeRoute = publicHomeRouteImport.update({
  id: '/(public)/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const publicForgotPasswordRoute = publicForgotPasswordRouteImport.update({
  id: '/(public)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1HealthRoute = ApiV1HealthRouteImport.update({
  id: '/api/v1/health',
  path: '/api/v1/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthSignUpRoute = ApiV1AuthSignUpRouteImport.update({
  id: '/api/v1/auth/sign-up',
  path: '/api/v1/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthSignOutRoute = ApiV1AuthSignOutRouteImport.update({
  id: '/api/v1/auth/sign-out',
  path: '/api/v1/auth/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthSignInRoute = ApiV1AuthSignInRouteImport.update({
  id: '/api/v1/auth/sign-in',
  path: '/api/v1/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthResetPasswordRoute = ApiV1AuthResetPasswordRouteImport.update({
  id: '/api/v1/auth/reset-password',
  path: '/api/v1/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthMeRoute = ApiV1AuthMeRouteImport.update({
  id: '/api/v1/auth/me',
  path: '/api/v1/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthForgotPasswordRoute = ApiV1AuthForgotPasswordRouteImport.update({
  id: '/api/v1/auth/forgot-password',
  path: '/api/v1/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthEmailStatusRoute = ApiV1AuthEmailStatusRouteImport.update({
  id: '/api/v1/auth/email-status',
  path: '/api/v1/auth/email-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AppwriteTablesRoute = ApiV1AppwriteTablesRouteImport.update({
  id: '/api/v1/appwrite/tables',
  path: '/api/v1/appwrite/tables',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AppwriteHealthRoute = ApiV1AppwriteHealthRouteImport.update({
  id: '/api/v1/appwrite/health',
  path: '/api/v1/appwrite/health',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/forgot-password': typeof publicForgotPasswordRoute
  '/home': typeof publicHomeRoute
  '/reset-password': typeof publicResetPasswordRoute
  '/reset-success': typeof publicResetSuccessRoute
  '/sign-in': typeof publicSignInRoute
  '/signup': typeof publicSignupRoute
  '/faculty/applications': typeof FacultyApplicationsRoute
  '/faculty/chat': typeof FacultyChatRoute
  '/faculty/documents': typeof FacultyDocumentsRoute
  '/panelist/chat': typeof PanelistChatRoute
  '/panelist/decisions': typeof PanelistDecisionsRoute
  '/panelist/reviews': typeof PanelistReviewsRoute
  '/': typeof publicIndexRoute
  '/faculty/': typeof FacultyIndexRoute
  '/panelist/': typeof PanelistIndexRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/appwrite/health': typeof ApiV1AppwriteHealthRoute
  '/api/v1/appwrite/tables': typeof ApiV1AppwriteTablesRoute
  '/api/v1/auth/email-status': typeof ApiV1AuthEmailStatusRoute
  '/api/v1/auth/forgot-password': typeof ApiV1AuthForgotPasswordRoute
  '/api/v1/auth/me': typeof ApiV1AuthMeRoute
  '/api/v1/auth/reset-password': typeof ApiV1AuthResetPasswordRoute
  '/api/v1/auth/sign-in': typeof ApiV1AuthSignInRoute
  '/api/v1/auth/sign-out': typeof ApiV1AuthSignOutRoute
  '/api/v1/auth/sign-up': typeof ApiV1AuthSignUpRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof publicForgotPasswordRoute
  '/home': typeof publicHomeRoute
  '/reset-password': typeof publicResetPasswordRoute
  '/reset-success': typeof publicResetSuccessRoute
  '/sign-in': typeof publicSignInRoute
  '/signup': typeof publicSignupRoute
  '/faculty/applications': typeof FacultyApplicationsRoute
  '/faculty/chat': typeof FacultyChatRoute
  '/faculty/documents': typeof FacultyDocumentsRoute
  '/panelist/chat': typeof PanelistChatRoute
  '/panelist/decisions': typeof PanelistDecisionsRoute
  '/panelist/reviews': typeof PanelistReviewsRoute
  '/': typeof publicIndexRoute
  '/faculty': typeof FacultyIndexRoute
  '/panelist': typeof PanelistIndexRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/appwrite/health': typeof ApiV1AppwriteHealthRoute
  '/api/v1/appwrite/tables': typeof ApiV1AppwriteTablesRoute
  '/api/v1/auth/email-status': typeof ApiV1AuthEmailStatusRoute
  '/api/v1/auth/forgot-password': typeof ApiV1AuthForgotPasswordRoute
  '/api/v1/auth/me': typeof ApiV1AuthMeRoute
  '/api/v1/auth/reset-password': typeof ApiV1AuthResetPasswordRoute
  '/api/v1/auth/sign-in': typeof ApiV1AuthSignInRoute
  '/api/v1/auth/sign-out': typeof ApiV1AuthSignOutRoute
  '/api/v1/auth/sign-up': typeof ApiV1AuthSignUpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(public)/forgot-password': typeof publicForgotPasswordRoute
  '/(public)/home': typeof publicHomeRoute
  '/(public)/reset-password': typeof publicResetPasswordRoute
  '/(public)/reset-success': typeof publicResetSuccessRoute
  '/(public)/sign-in': typeof publicSignInRoute
  '/(public)/signup': typeof publicSignupRoute
  '/faculty/applications': typeof FacultyApplicationsRoute
  '/faculty/chat': typeof FacultyChatRoute
  '/faculty/documents': typeof FacultyDocumentsRoute
  '/panelist/chat': typeof PanelistChatRoute
  '/panelist/decisions': typeof PanelistDecisionsRoute
  '/panelist/reviews': typeof PanelistReviewsRoute
  '/(public)/': typeof publicIndexRoute
  '/faculty/': typeof FacultyIndexRoute
  '/panelist/': typeof PanelistIndexRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/appwrite/health': typeof ApiV1AppwriteHealthRoute
  '/api/v1/appwrite/tables': typeof ApiV1AppwriteTablesRoute
  '/api/v1/auth/email-status': typeof ApiV1AuthEmailStatusRoute
  '/api/v1/auth/forgot-password': typeof ApiV1AuthForgotPasswordRoute
  '/api/v1/auth/me': typeof ApiV1AuthMeRoute
  '/api/v1/auth/reset-password': typeof ApiV1AuthResetPasswordRoute
  '/api/v1/auth/sign-in': typeof ApiV1AuthSignInRoute
  '/api/v1/auth/sign-out': typeof ApiV1AuthSignOutRoute
  '/api/v1/auth/sign-up': typeof ApiV1AuthSignUpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/forgot-password'
    | '/home'
    | '/reset-password'
    | '/reset-success'
    | '/sign-in'
    | '/signup'
    | '/faculty/applications'
    | '/faculty/chat'
    | '/faculty/documents'
    | '/panelist/chat'
    | '/panelist/decisions'
    | '/panelist/reviews'
    | '/'
    | '/faculty/'
    | '/panelist/'
    | '/api/v1/health'
    | '/api/v1/appwrite/health'
    | '/api/v1/appwrite/tables'
    | '/api/v1/auth/email-status'
    | '/api/v1/auth/forgot-password'
    | '/api/v1/auth/me'
    | '/api/v1/auth/reset-password'
    | '/api/v1/auth/sign-in'
    | '/api/v1/auth/sign-out'
    | '/api/v1/auth/sign-up'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/home'
    | '/reset-password'
    | '/reset-success'
    | '/sign-in'
    | '/signup'
    | '/faculty/applications'
    | '/faculty/chat'
    | '/faculty/documents'
    | '/panelist/chat'
    | '/panelist/decisions'
    | '/panelist/reviews'
    | '/'
    | '/faculty'
    | '/panelist'
    | '/api/v1/health'
    | '/api/v1/appwrite/health'
    | '/api/v1/appwrite/tables'
    | '/api/v1/auth/email-status'
    | '/api/v1/auth/forgot-password'
    | '/api/v1/auth/me'
    | '/api/v1/auth/reset-password'
    | '/api/v1/auth/sign-in'
    | '/api/v1/auth/sign-out'
    | '/api/v1/auth/sign-up'
  id:
    | '__root__'
    | '/(public)/forgot-password'
    | '/(public)/home'
    | '/(public)/reset-password'
    | '/(public)/reset-success'
    | '/(public)/sign-in'
    | '/(public)/signup'
    | '/faculty/applications'
    | '/faculty/chat'
    | '/faculty/documents'
    | '/panelist/chat'
    | '/panelist/decisions'
    | '/panelist/reviews'
    | '/(public)/'
    | '/faculty/'
    | '/panelist/'
    | '/api/v1/health'
    | '/api/v1/appwrite/health'
    | '/api/v1/appwrite/tables'
    | '/api/v1/auth/email-status'
    | '/api/v1/auth/forgot-password'
    | '/api/v1/auth/me'
    | '/api/v1/auth/reset-password'
    | '/api/v1/auth/sign-in'
    | '/api/v1/auth/sign-out'
    | '/api/v1/auth/sign-up'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  publicForgotPasswordRoute: typeof publicForgotPasswordRoute
  publicHomeRoute: typeof publicHomeRoute
  publicResetPasswordRoute: typeof publicResetPasswordRoute
  publicResetSuccessRoute: typeof publicResetSuccessRoute
  publicSignInRoute: typeof publicSignInRoute
  publicSignupRoute: typeof publicSignupRoute
  FacultyApplicationsRoute: typeof FacultyApplicationsRoute
  FacultyChatRoute: typeof FacultyChatRoute
  FacultyDocumentsRoute: typeof FacultyDocumentsRoute
  PanelistChatRoute: typeof PanelistChatRoute
  PanelistDecisionsRoute: typeof PanelistDecisionsRoute
  PanelistReviewsRoute: typeof PanelistReviewsRoute
  publicIndexRoute: typeof publicIndexRoute
  FacultyIndexRoute: typeof FacultyIndexRoute
  PanelistIndexRoute: typeof PanelistIndexRoute
  ApiV1HealthRoute: typeof ApiV1HealthRoute
  ApiV1AppwriteHealthRoute: typeof ApiV1AppwriteHealthRoute
  ApiV1AppwriteTablesRoute: typeof ApiV1AppwriteTablesRoute
  ApiV1AuthEmailStatusRoute: typeof ApiV1AuthEmailStatusRoute
  ApiV1AuthForgotPasswordRoute: typeof ApiV1AuthForgotPasswordRoute
  ApiV1AuthMeRoute: typeof ApiV1AuthMeRoute
  ApiV1AuthResetPasswordRoute: typeof ApiV1AuthResetPasswordRoute
  ApiV1AuthSignInRoute: typeof ApiV1AuthSignInRoute
  ApiV1AuthSignOutRoute: typeof ApiV1AuthSignOutRoute
  ApiV1AuthSignUpRoute: typeof ApiV1AuthSignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/panelist/': {
      id: '/panelist/'
      path: '/panelist'
      fullPath: '/panelist/'
      preLoaderRoute: typeof PanelistIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/': {
      id: '/faculty/'
      path: '/faculty'
      fullPath: '/faculty/'
      preLoaderRoute: typeof FacultyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panelist/reviews': {
      id: '/panelist/reviews'
      path: '/panelist/reviews'
      fullPath: '/panelist/reviews'
      preLoaderRoute: typeof PanelistReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panelist/decisions': {
      id: '/panelist/decisions'
      path: '/panelist/decisions'
      fullPath: '/panelist/decisions'
      preLoaderRoute: typeof PanelistDecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panelist/chat': {
      id: '/panelist/chat'
      path: '/panelist/chat'
      fullPath: '/panelist/chat'
      preLoaderRoute: typeof PanelistChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/documents': {
      id: '/faculty/documents'
      path: '/faculty/documents'
      fullPath: '/faculty/documents'
      preLoaderRoute: typeof FacultyDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/chat': {
      id: '/faculty/chat'
      path: '/faculty/chat'
      fullPath: '/faculty/chat'
      preLoaderRoute: typeof FacultyChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/applications': {
      id: '/faculty/applications'
      path: '/faculty/applications'
      fullPath: '/faculty/applications'
      preLoaderRoute: typeof FacultyApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/signup': {
      id: '/(public)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof publicSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/sign-in': {
      id: '/(public)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof publicSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/reset-success': {
      id: '/(public)/reset-success'
      path: '/reset-success'
      fullPath: '/reset-success'
      preLoaderRoute: typeof publicResetSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/reset-password': {
      id: '/(public)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof publicResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/home': {
      id: '/(public)/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof publicHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/forgot-password': {
      id: '/(public)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof publicForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/health': {
      id: '/api/v1/health'
      path: '/api/v1/health'
      fullPath: '/api/v1/health'
      preLoaderRoute: typeof ApiV1HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/sign-up': {
      id: '/api/v1/auth/sign-up'
      path: '/api/v1/auth/sign-up'
      fullPath: '/api/v1/auth/sign-up'
      preLoaderRoute: typeof ApiV1AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/sign-out': {
      id: '/api/v1/auth/sign-out'
      path: '/api/v1/auth/sign-out'
      fullPath: '/api/v1/auth/sign-out'
      preLoaderRoute: typeof ApiV1AuthSignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/sign-in': {
      id: '/api/v1/auth/sign-in'
      path: '/api/v1/auth/sign-in'
      fullPath: '/api/v1/auth/sign-in'
      preLoaderRoute: typeof ApiV1AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/reset-password': {
      id: '/api/v1/auth/reset-password'
      path: '/api/v1/auth/reset-password'
      fullPath: '/api/v1/auth/reset-password'
      preLoaderRoute: typeof ApiV1AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/me': {
      id: '/api/v1/auth/me'
      path: '/api/v1/auth/me'
      fullPath: '/api/v1/auth/me'
      preLoaderRoute: typeof ApiV1AuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/forgot-password': {
      id: '/api/v1/auth/forgot-password'
      path: '/api/v1/auth/forgot-password'
      fullPath: '/api/v1/auth/forgot-password'
      preLoaderRoute: typeof ApiV1AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/email-status': {
      id: '/api/v1/auth/email-status'
      path: '/api/v1/auth/email-status'
      fullPath: '/api/v1/auth/email-status'
      preLoaderRoute: typeof ApiV1AuthEmailStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/appwrite/tables': {
      id: '/api/v1/appwrite/tables'
      path: '/api/v1/appwrite/tables'
      fullPath: '/api/v1/appwrite/tables'
      preLoaderRoute: typeof ApiV1AppwriteTablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/appwrite/health': {
      id: '/api/v1/appwrite/health'
      path: '/api/v1/appwrite/health'
      fullPath: '/api/v1/appwrite/health'
      preLoaderRoute: typeof ApiV1AppwriteHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  publicForgotPasswordRoute: publicForgotPasswordRoute,
  publicHomeRoute: publicHomeRoute,
  publicResetPasswordRoute: publicResetPasswordRoute,
  publicResetSuccessRoute: publicResetSuccessRoute,
  publicSignInRoute: publicSignInRoute,
  publicSignupRoute: publicSignupRoute,
  FacultyApplicationsRoute: FacultyApplicationsRoute,
  FacultyChatRoute: FacultyChatRoute,
  FacultyDocumentsRoute: FacultyDocumentsRoute,
  PanelistChatRoute: PanelistChatRoute,
  PanelistDecisionsRoute: PanelistDecisionsRoute,
  PanelistReviewsRoute: PanelistReviewsRoute,
  publicIndexRoute: publicIndexRoute,
  FacultyIndexRoute: FacultyIndexRoute,
  PanelistIndexRoute: PanelistIndexRoute,
  ApiV1HealthRoute: ApiV1HealthRoute,
  ApiV1AppwriteHealthRoute: ApiV1AppwriteHealthRoute,
  ApiV1AppwriteTablesRoute: ApiV1AppwriteTablesRoute,
  ApiV1AuthEmailStatusRoute: ApiV1AuthEmailStatusRoute,
  ApiV1AuthForgotPasswordRoute: ApiV1AuthForgotPasswordRoute,
  ApiV1AuthMeRoute: ApiV1AuthMeRoute,
  ApiV1AuthResetPasswordRoute: ApiV1AuthResetPasswordRoute,
  ApiV1AuthSignInRoute: ApiV1AuthSignInRoute,
  ApiV1AuthSignOutRoute: ApiV1AuthSignOutRoute,
  ApiV1AuthSignUpRoute: ApiV1AuthSignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
